/*

CREATE PROCEDURE sp_mudabanco @BDOrigem NVARCHAR(100), @BDDestino NVARCHAR(100)
AS
  ALTER DATABASE @BDOrigem SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  ALTER DATABASE @BDOrigem MODIFY NAME = @BDDestino;
  ALTER DATABASE @BDDestino SET MULTI_USER
GO

*/

--SysacME = MOSSORO

--// Modificando de SysacME para outra
USE master;  
GO  
ALTER DATABASE SysacME SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
ALTER DATABASE SysacME MODIFY NAME = SUPERJOTA ;
GO  
ALTER DATABASE SUPERJOTA SET MULTI_USER
GO


--// Modificando de outra para SysacME
USE master;  
GO  
ALTER DATABASE SUPERJOTA SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
ALTER DATABASE SUPERJOTA MODIFY NAME = SysacME ;
GO  
ALTER DATABASE SysacME SET MULTI_USER
GO








